"""Shell integration: `nsxctl completion`, `nsxctl menu`, `nsxctl version`.

The completion scripts are generated by walking the live argparse tree, never
hand-written, so a command added tomorrow is completable tomorrow and the
scripts cannot drift from the real surface.

Flags are one thing; the names an engineer actually types are another.
`--policy <TAB>` completing nothing is most of the daily friction, so the
scripts also complete group, policy, service and rule NAMES -- out of a cache
file, never out of NSX. **Pressing TAB must not make a network call**: see
namecache.py for why that rule is absolute.
"""

import argparse

from ..config import find_inventory, resolve_profile
from ..namecache import (
    CACHE_KINDS,
    KIND_GROUP,
    KIND_MANAGER,
    KIND_POLICY,
    KIND_PROFILE,
    KIND_RULE,
    KIND_SERVICE,
    cache_age,
    cache_path,
    cached_names,
    describe_age,
    refresh_from_nsx,
)
from ..output import cBY, cC, cD, err, hr, ok_msg, say, section, table
from ..paths import config_search_dirs
from ..version import TOOL_NAME, VERSION, VERSION_DATE
from . import PROG, add_command

SHELLS = ("bash", "zsh", "fish")

# `completion <shell>` prints a script and needs no NSX at all; `completion
# cache` reads the whole estate. Same command, opposite requirements, which is
# why the requirement is set from the value rather than on the parser.
CACHE_TARGET = "cache"


class _CompletionTarget(argparse.Action):
    """Set the NSX requirement from which target was asked for."""

    def __call__(self, parser, namespace, value, option_string=None):
        setattr(namespace, self.dest, value)
        needs_nsx = value == CACHE_TARGET
        namespace.needs_inventory = needs_nsx
        namespace.needs_sessions = needs_nsx

# Which cached names an option takes. Everything not listed completes files,
# which is the right default for --out-csv and friends.
OPTION_VALUE_KINDS = {
    "--policy": KIND_POLICY,
    "--service": KIND_SERVICE,
    "--from": KIND_GROUP,
    "--to": KIND_GROUP,
    "--applied-to": KIND_GROUP,
    "--manager": KIND_MANAGER,
    "--profile": KIND_PROFILE,
    "--before": KIND_RULE,
    "--after": KIND_RULE,
    "--contains": "",          # free text: complete nothing rather than lie
}

# Which cached names a subcommand's first positional takes.
POSITIONAL_VALUE_KINDS = {
    ("group", "show"): KIND_GROUP,
    ("group", "edit"): KIND_GROUP,
    ("group", "delete"): KIND_GROUP,
    ("rule", "show"): KIND_RULE,
    ("rule", "edit"): KIND_RULE,
    ("rule", "move"): KIND_RULE,
    ("rule", "delete"): KIND_RULE,
    ("service", "show"): KIND_SERVICE,
    ("login", ""): KIND_MANAGER,
}


def register_shell(sub, parents):
    p = add_command(
        sub, parents, "menu", "Open the interactive menu.",
        description="The guided menu. Running nsxctl with no arguments does "
                    "the same thing.")
    p.set_defaults(func=cmd_menu)

    p = add_command(
        sub, parents, "completion", "Print a shell completion script.",
        description="Generated from the command tree, so it always matches "
                    "the commands this build actually has.",
        epilog="install:\n"
               "  bash   nsxctl completion bash > "
               "/etc/bash_completion.d/nsxctl\n"
               "  zsh    nsxctl completion zsh  > "
               "\"${fpath[1]}/_nsxctl\"\n"
               "  fish   nsxctl completion fish > "
               "~/.config/fish/completions/nsxctl.fish")
    p.add_argument("target", nargs="?", choices=SHELLS + (CACHE_TARGET,),
                   action=_CompletionTarget, metavar="TARGET",
                   help="{} to print that shell's script, or '{}' to refresh "
                        "the name cache.".format(" | ".join(SHELLS),
                                                 CACHE_TARGET))
    p.add_argument("--status", action="store_true",
                   help="With '{}': report what is cached without refreshing "
                        "it.".format(CACHE_TARGET))
    p.set_defaults(func=cmd_completion, needs_inventory=False,
                   needs_sessions=False)

    p = add_command(
        sub, parents, "__complete", argparse.SUPPRESS,
        description="Internal: print cached names for shell completion. "
                    "Reads a file and never touches NSX.")
    p.add_argument("kind", choices=CACHE_KINDS)
    p.add_argument("prefix", nargs="?", default="")
    p.set_defaults(func=cmd_internal_complete, needs_inventory=False,
                   needs_sessions=False)

    p = add_command(sub, parents, "version", "Print the version and exit.")
    p.set_defaults(func=cmd_version, needs_inventory=False,
                   needs_sessions=False)


def cmd_menu(args, ctx):
    from ..menu import interactive
    return interactive(ctx)


def cmd_version(args, ctx):
    say("{} v{} ({})".format(TOOL_NAME, VERSION, VERSION_DATE))
    return 0


# === PARSER INTROSPECTION ===
def _completion_options(parser):
    out = []
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            continue
        out.extend(s for s in action.option_strings if s.startswith("--"))
    return sorted(set(out))


def _completion_subparsers(parser):
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action.choices
    return {}


def command_tree(parser):
    """{command: {"options": [...], "subcommands": {name: [options]}}}"""
    tree = {}
    for name, cmd_parser in _completion_subparsers(parser).items():
        entry = {"options": _completion_options(cmd_parser), "subcommands": {}}
        for sub_name, sub_parser in _completion_subparsers(cmd_parser).items():
            entry["subcommands"][sub_name] = _completion_options(sub_parser)
        tree[name] = entry
    return tree


def _tree_and_globals():
    from . import build_parser
    parser = build_parser()
    return command_tree(parser), _completion_options(parser)


# === EMITTERS ===
def _completion_bash(tree, global_opts):
    commands = " ".join(sorted(tree))
    lines = [
        "# {} completion for bash -- generated by `{} completion bash`".format(
            PROG, PROG),
        "_{}() {{".format(PROG),
        '    local cur cmd sub i',
        '    cur="${COMP_WORDS[COMP_CWORD]}"',
        '    cmd=""; sub=""',
        '    for ((i=1; i<COMP_CWORD; i++)); do',
        '        case "${COMP_WORDS[i]}" in',
        '            -*) continue ;;',
        '            *)  if [ -z "$cmd" ]; then cmd="${COMP_WORDS[i]}";',
        '                elif [ -z "$sub" ]; then sub="${COMP_WORDS[i]}"; fi ;;',
        '        esac',
        '    done',
        '    local commands="{}"'.format(commands),
        '    local globals="{}"'.format(" ".join(global_opts)),
        '    if [ -z "$cmd" ]; then',
        '        if [[ "$cur" == -* ]]; then',
        '            COMPREPLY=( $(compgen -W "$globals" -- "$cur") )',
        '        else',
        '            COMPREPLY=( $(compgen -W "$commands" -- "$cur") )',
        '        fi',
        '        return',
        '    fi',
        '    local subs="" opts="$globals"',
        '    case "$cmd" in',
    ]
    for name in sorted(tree):
        entry = tree[name]
        subs = " ".join(sorted(entry["subcommands"]))
        opts = " ".join(sorted(set(entry["options"]) | set(global_opts)))
        lines.append('        {}) subs="{}"; opts="{}" ;;'.format(
            name, subs, opts))
    lines.extend([
        '    esac',
        '    local prev="${COMP_WORDS[COMP_CWORD-1]}" kind=""',
        '    case "$prev" in',
    ])
    for option, kind in sorted(OPTION_VALUE_KINDS.items()):
        lines.append('        {}) kind="{}" ;;'.format(option, kind))
    lines.extend([
        '    esac',
        '    if [ -n "$kind" ]; then',
        # Reads a cache file. Never a network call -- see namecache.py.
        '        COMPREPLY=( $(compgen -W "$({} __complete "$kind" '
        '2>/dev/null)" -- "$cur") )'.format(PROG),
        '        return',
        '    fi',
        '    if [[ "$prev" == -* ]] && [ -z "$kind" ]; then',
        '        case "$prev" in',
        '            --out-csv|--out-json|--out-html|--inventory|--taxonomy'
        '|--ca-bundle|--baseline-file)',
        '                COMPREPLY=( $(compgen -f -- "$cur") ); return ;;',
        '        esac',
        '    fi',
        '    if [[ "$cur" == -* ]]; then',
        '        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )',
        '        return',
        '    fi',
        '    if [ -n "$subs" ] && [ -z "$sub" ]; then',
        '        COMPREPLY=( $(compgen -W "$subs" -- "$cur") )',
        '        return',
        '    fi',
        '    local poskind=""',
        '    case "$cmd $sub" in',
    ])
    for (command, subcommand), kind in sorted(POSITIONAL_VALUE_KINDS.items()):
        lines.append('        "{} {}") poskind="{}" ;;'.format(
            command, subcommand, kind))
    lines.extend([
        '    esac',
        '    if [ -n "$poskind" ]; then',
        '        COMPREPLY=( $(compgen -W "$({} __complete "$poskind" '
        '2>/dev/null)" -- "$cur") )'.format(PROG),
        '    else',
        '        COMPREPLY=( $(compgen -f -- "$cur") )',
        '    fi',
        "}",
        "complete -F _{} {}".format(PROG, PROG),
    ])
    return "\n".join(lines) + "\n"


def _completion_zsh(tree, global_opts):
    lines = [
        "#compdef {}".format(PROG),
        "# generated by `{} completion zsh`".format(PROG),
        "_{}() {{".format(PROG),
        "    local -a commands",
        "    commands=({})".format(
            " ".join("'{}'".format(c) for c in sorted(tree))),
        "    if (( CURRENT == 2 )); then",
        "        _describe 'command' commands",
        "        return",
        "    fi",
        "    case \"${words[2]}\" in",
    ]
    for name in sorted(tree):
        subs = sorted(tree[name]["subcommands"])
        if subs:
            lines.append("        {})".format(name))
            lines.append("            if (( CURRENT == 3 )); then")
            lines.append("                _values 'action' {}".format(
                " ".join("'{}'".format(s) for s in subs)))
            lines.append("            else")
            lines.append("                _files")
            lines.append("            fi ;;")
        else:
            lines.append("        {}) _files ;;".format(name))
    lines.extend([
        "    esac",
        "    local prev=\"${words[CURRENT-1]}\" kind=\"\"",
        "    case \"$prev\" in",
    ])
    for option, kind in sorted(OPTION_VALUE_KINDS.items()):
        if kind:
            lines.append("        {}) kind={} ;;".format(option, kind))
    lines.extend([
        "    esac",
        "    if [[ -n \"$kind\" ]]; then",
        # A cache read, not a network call.
        "        local -a vals; vals=(${{(f)\"$({} __complete $kind "
        "2>/dev/null)\"}})".format(PROG),
        "        _describe 'name' vals",
        "    fi",
        "}",
        "_{} \"$@\"".format(PROG),
    ])
    return "\n".join(lines) + "\n"


def _completion_fish(tree, global_opts):
    lines = ["# generated by `{} completion fish`".format(PROG)]
    has_cmd = "__fish_seen_subcommand_from"
    lines.append("function __{}_no_command".format(PROG))
    lines.append("    not {} {}".format(has_cmd, " ".join(sorted(tree))))
    lines.append("end")
    for name in sorted(tree):
        lines.append(
            "complete -c {} -n '__{}_no_command' -a '{}'".format(
                PROG, PROG, name))
        for sub in sorted(tree[name]["subcommands"]):
            lines.append(
                "complete -c {} -n '{} {}' -a '{}'".format(
                    PROG, has_cmd, name, sub))
    for opt in global_opts:
        lines.append("complete -c {} -l '{}'".format(PROG, opt.lstrip("-")))
    # Value completion reads the cache; fish runs this per keystroke, so it
    # must stay a file read.
    for option, kind in sorted(OPTION_VALUE_KINDS.items()):
        if not kind:
            continue
        lines.append(
            "complete -c {} -l '{}' -f -a '({} __complete {} 2>/dev/null)'"
            .format(PROG, option.lstrip("-"), PROG, kind))
    return "\n".join(lines) + "\n"


COMPLETION_EMITTERS = {"bash": _completion_bash,
                       "zsh": _completion_zsh,
                       "fish": _completion_fish}


def completion_script(shell):
    tree, global_opts = _tree_and_globals()
    return COMPLETION_EMITTERS[shell](tree, global_opts)


def cmd_completion(args, ctx):
    if args.target == CACHE_TARGET:
        return cmd_completion_cache(args, ctx)
    if not args.target:
        err("Which shell? {}   (or '{}' to refresh the name cache)".format(
            " | ".join(SHELLS), CACHE_TARGET))
        return 2
    # print(), not say(): this is data piped into a file, so it must be
    # emitted even when --json or a quiet mode is in effect.
    print(completion_script(args.target), end="")
    return 0


def _completion_profile(args):
    """Which cache to read, worked out without loading anything expensive.

    This command runs with needs_inventory=False on purpose: if the inventory
    were loaded the normal way, a shell hook on a machine with no config would
    trigger the first-run WIZARD, at a prompt, from a TAB press. So the file is
    read directly, only if it already exists, and every failure resolves to the
    default cache rather than being reported.
    """
    if getattr(args, "profile", None):
        return args.profile
    try:
        path = find_inventory(getattr(args, "inventory", None),
                              config_search_dirs())
        if not path:
            return None
        return resolve_profile(path)[0]
    except Exception:  # noqa: BLE001 - never fail loudly inside a shell hook
        return None


def cmd_internal_complete(args, ctx):
    """Print cached names, one per line. Never touches the network.

    Deliberately tolerant of everything: this runs inside a shell hook where
    an error message would be printed over the user's prompt.
    """
    try:
        profile = _completion_profile(args)
        project = getattr(args, "project", None)
        names = cached_names(args.kind, profile, project)
        if not names and profile:
            # A cache written before the profile existed, or under a different
            # one. Falling back to the default is better than offering nothing.
            names = cached_names(args.kind, None, project)
    except Exception:  # noqa: BLE001 - a completion hook must never fail loudly
        return 0
    prefix = args.prefix or ""
    for name in names:
        if name.startswith(prefix):
            print(name)
    return 0


def cmd_completion_cache(args, ctx):
    section("COMPLETION NAME CACHE")
    profile = getattr(ctx, "profile", None)
    project = getattr(ctx, "project", None)
    path = cache_path(profile, project)
    age = cache_age(profile, project)

    if args.status:
        say("  File   : {}".format(cC(path)))
        say("  Written: {}".format(describe_age(age)))
        rows = [[kind, str(len(cached_names(kind, profile, project)))]
                for kind in CACHE_KINDS]
        table(["Kind", "Names"], rows, indent=4)
        if age is None:
            say("\n  {} run `nsxctl completion cache` to build it.".format(
                cBY("Empty:")))
        return 0

    written, counts = refresh_from_nsx(ctx.sessions, args.domain,
                                       profile=profile, project=project)
    if not written:
        say("  {} the cache could not be written; completion will simply "
            "offer nothing.".format(cBY("Note:")))
        return 0
    table(["Kind", "Names"],
          [[k, str(v)] for k, v in sorted(counts.items())], indent=4)
    hr()
    ok_msg("Cached: {}".format(written))
    say("  {}".format(cD(
        "TAB now completes these names without talking to NSX.")))
    return 0
