"""Shell integration: `nsxctl completion`, `nsxctl menu`, `nsxctl version`.

The completion scripts are generated by walking the live argparse tree, never
hand-written, so a command added tomorrow is completable tomorrow and the
scripts cannot drift from the real surface.
"""

import argparse

from ..output import say
from ..version import TOOL_NAME, VERSION, VERSION_DATE
from . import PROG, add_command

SHELLS = ("bash", "zsh", "fish")


def register_shell(sub, parents):
    p = add_command(
        sub, parents, "menu", "Open the interactive menu.",
        description="The guided menu. Running nsxctl with no arguments does "
                    "the same thing.")
    p.set_defaults(func=cmd_menu)

    p = add_command(
        sub, parents, "completion", "Print a shell completion script.",
        description="Generated from the command tree, so it always matches "
                    "the commands this build actually has.",
        epilog="install:\n"
               "  bash   nsxctl completion bash > "
               "/etc/bash_completion.d/nsxctl\n"
               "  zsh    nsxctl completion zsh  > "
               "\"${fpath[1]}/_nsxctl\"\n"
               "  fish   nsxctl completion fish > "
               "~/.config/fish/completions/nsxctl.fish")
    p.add_argument("shell", choices=SHELLS)
    p.set_defaults(func=cmd_completion, needs_inventory=False,
                   needs_sessions=False)

    p = add_command(sub, parents, "version", "Print the version and exit.")
    p.set_defaults(func=cmd_version, needs_inventory=False,
                   needs_sessions=False)


def cmd_menu(args, ctx):
    from ..menu import interactive
    return interactive(ctx)


def cmd_version(args, ctx):
    say("{} v{} ({})".format(TOOL_NAME, VERSION, VERSION_DATE))
    return 0


# === PARSER INTROSPECTION ===
def _completion_options(parser):
    out = []
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            continue
        out.extend(s for s in action.option_strings if s.startswith("--"))
    return sorted(set(out))


def _completion_subparsers(parser):
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action.choices
    return {}


def command_tree(parser):
    """{command: {"options": [...], "subcommands": {name: [options]}}}"""
    tree = {}
    for name, cmd_parser in _completion_subparsers(parser).items():
        entry = {"options": _completion_options(cmd_parser), "subcommands": {}}
        for sub_name, sub_parser in _completion_subparsers(cmd_parser).items():
            entry["subcommands"][sub_name] = _completion_options(sub_parser)
        tree[name] = entry
    return tree


def _tree_and_globals():
    from . import build_parser
    parser = build_parser()
    return command_tree(parser), _completion_options(parser)


# === EMITTERS ===
def _completion_bash(tree, global_opts):
    commands = " ".join(sorted(tree))
    lines = [
        "# {} completion for bash -- generated by `{} completion bash`".format(
            PROG, PROG),
        "_{}() {{".format(PROG),
        '    local cur cmd sub i',
        '    cur="${COMP_WORDS[COMP_CWORD]}"',
        '    cmd=""; sub=""',
        '    for ((i=1; i<COMP_CWORD; i++)); do',
        '        case "${COMP_WORDS[i]}" in',
        '            -*) continue ;;',
        '            *)  if [ -z "$cmd" ]; then cmd="${COMP_WORDS[i]}";',
        '                elif [ -z "$sub" ]; then sub="${COMP_WORDS[i]}"; fi ;;',
        '        esac',
        '    done',
        '    local commands="{}"'.format(commands),
        '    local globals="{}"'.format(" ".join(global_opts)),
        '    if [ -z "$cmd" ]; then',
        '        if [[ "$cur" == -* ]]; then',
        '            COMPREPLY=( $(compgen -W "$globals" -- "$cur") )',
        '        else',
        '            COMPREPLY=( $(compgen -W "$commands" -- "$cur") )',
        '        fi',
        '        return',
        '    fi',
        '    local subs="" opts="$globals"',
        '    case "$cmd" in',
    ]
    for name in sorted(tree):
        entry = tree[name]
        subs = " ".join(sorted(entry["subcommands"]))
        opts = " ".join(sorted(set(entry["options"]) | set(global_opts)))
        lines.append('        {}) subs="{}"; opts="{}" ;;'.format(
            name, subs, opts))
    lines.extend([
        '    esac',
        '    if [[ "$cur" == -* ]]; then',
        '        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )',
        '    elif [ -n "$subs" ] && [ -z "$sub" ]; then',
        '        COMPREPLY=( $(compgen -W "$subs" -- "$cur") )',
        '    else',
        '        COMPREPLY=( $(compgen -f -- "$cur") )',
        '    fi',
        "}",
        "complete -F _{} {}".format(PROG, PROG),
    ])
    return "\n".join(lines) + "\n"


def _completion_zsh(tree, global_opts):
    lines = [
        "#compdef {}".format(PROG),
        "# generated by `{} completion zsh`".format(PROG),
        "_{}() {{".format(PROG),
        "    local -a commands",
        "    commands=({})".format(
            " ".join("'{}'".format(c) for c in sorted(tree))),
        "    if (( CURRENT == 2 )); then",
        "        _describe 'command' commands",
        "        return",
        "    fi",
        "    case \"${words[2]}\" in",
    ]
    for name in sorted(tree):
        subs = sorted(tree[name]["subcommands"])
        if subs:
            lines.append("        {})".format(name))
            lines.append("            if (( CURRENT == 3 )); then")
            lines.append("                _values 'action' {}".format(
                " ".join("'{}'".format(s) for s in subs)))
            lines.append("            else")
            lines.append("                _files")
            lines.append("            fi ;;")
        else:
            lines.append("        {}) _files ;;".format(name))
    lines.extend([
        "    esac",
        "}",
        "_{} \"$@\"".format(PROG),
    ])
    return "\n".join(lines) + "\n"


def _completion_fish(tree, global_opts):
    lines = ["# generated by `{} completion fish`".format(PROG)]
    has_cmd = "__fish_seen_subcommand_from"
    lines.append("function __{}_no_command".format(PROG))
    lines.append("    not {} {}".format(has_cmd, " ".join(sorted(tree))))
    lines.append("end")
    for name in sorted(tree):
        lines.append(
            "complete -c {} -n '__{}_no_command' -a '{}'".format(
                PROG, PROG, name))
        for sub in sorted(tree[name]["subcommands"]):
            lines.append(
                "complete -c {} -n '{} {}' -a '{}'".format(
                    PROG, has_cmd, name, sub))
    for opt in global_opts:
        lines.append("complete -c {} -l '{}'".format(PROG, opt.lstrip("-")))
    return "\n".join(lines) + "\n"


COMPLETION_EMITTERS = {"bash": _completion_bash,
                       "zsh": _completion_zsh,
                       "fish": _completion_fish}


def completion_script(shell):
    tree, global_opts = _tree_and_globals()
    return COMPLETION_EMITTERS[shell](tree, global_opts)


def cmd_completion(args, ctx):
    # print(), not say(): this is data piped into a file, so it must be
    # emitted even when --json or a quiet mode is in effect.
    print(completion_script(args.shell), end="")
    return 0
